CREATE TABLE users (
  id 
      INTEGER GENERATED BY DEFAULT AS IDENTITY 
      UNIQUE,
  username 
      TEXT 
      NOT NULL 
      UNIQUE,
  password 
      TEXT 
      NOT NULL,
  created_at
      TIMESTAMP 
      NOT NULL 
      DEFAULT now(),
  updated_at
      TIMESTAMP
      DEFAULT now()
);